### ISSUE TITLE
Plugin incompatible with PMD Eclipse 4.0.13.v20170429-1921 / PMD 5.6.1

### ISSUE THREAD

**Issue by sayresVT** [m2e-code-quality/m2e-code-quality#105]
The latest version of the PMD Eclipse plugin, 4.0.13.v20170429-1921, was updated to use PMD 5.6.1.  This appears to have introduced API changes that are currently incompatible with this plugin.  It looks like the RuleSet can only be instantiated through a RuleSetFactory as of PMD 5.6.0.  

This is the exception that I'm seeing in Eclipse:

	java.lang.NoSuchMethodError: net.sourceforge.pmd.RuleSet: method <init>()V not found
		at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.createPmdRuleSet(EclipsePmdProjectConfigurator.java:223)
		at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.createOrUpdateEclipsePmdConfiguration(EclipsePmdProjectConfigurator.java:190)
		at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.handleProjectConfigurationChange(EclipsePmdProjectConfigurator.java:109)
		at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:181)
		at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:1000)
		at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:783)
		at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:930)
		at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:300)
		at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:398)
		at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:345)
		at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
		at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
		at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
		at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
		at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
		at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:342)
		at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
		at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
		at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by ggerla** [comment]
I have the same problem.
Is there a workaround?

**Comment by sayresVT** [comment]
I believe the previous 4.0.12 version of the PMD Eclipse plugin is still compatible due to an older version of PMD (pre-5.6.0) being used.  I don't know if this works for your situation but here's the update site for the 4.0.12 PMD Eclipse plugin: https://dl.bintray.com/pmd/pmd-eclipse-plugin/releases/4.0.12.v20170331-0813

**Comment by ggerla** [comment]
I solved the problem using maven-pmd-plugin 3.7 (instead 3.8) in maven pom. in this way eclipse installed 4.0.12.v20170331-0813 (as you suggested).

Thanks

**Comment by ArloL** [comment]
I have looked into the problem for an hour now and can't find my way around the new structure of PMD. It seems that I have to somehow start using the RuleSetFactory or something. Since I am not a PMD user I will stop working on this for now. I will gladly accept and help with PRs though.

**Comment by ArloL** [comment]
Can you try with the following update site?

https://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by ArloL** [comment]
Hi @sayresVT and @ggerla, I would like to release the changes sometime soon. Would you be able to find some time and try the `develop` update site? That way I can be confident in a release. That would be very helpful. Thanks 😄

**Comment by sayresVT** [comment]
I've been testing against the latest update and everything is looking good so far!  

There was a minor hiccup with a renamed rule, UnusedModifier, that I suspect was being picked up from .metadata\.plugins\net.sourceforge.pmd.eclipse.plugin\ruleset.xml because our rule file doesn't reference it.  But I'm assuming that was more of an issue with the PMD Eclipse plugin not initially updating that ruleset.xml with the latest rules (eventually it did though).

Thanks for following up @ArloL and thanks for the fix @adangel !

**Comment by ArloL** [comment]
1.0.0.201705301746 is now available from the release update site.
