### ISSUE TITLE
No suppressionsLocation configured make the checkstyle m2e configurator crash

### ISSUE THREAD

**Issue by victornoel** [m2e-code-quality/m2e-code-quality#150]
I just tried to run the latest version of the plugins and I got the following error:
```
!ENTRY org.eclipse.core.jobs 4 2 2018-09-19 19:14:55.731
!MESSAGE An internal error occurred during: "Updating Maven Project".
!STACK 0
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:180)
	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginConfigurationTranslator.resolveLocation(AbstractMavenPluginConfigurationTranslator.java:142)
	at com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.getSuppressionsLocation(MavenPluginConfigurationTranslator.java:230)
	at com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.getSuppressionsFile(MavenPluginConfigurationTranslator.java:118)
	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.buildCheckstyleConfiguration(EclipseCheckstyleProjectConfigurator.java:164)
	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.handleProjectConfigurationChange(EclipseCheckstyleProjectConfigurator.java:107)
	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:181)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:1037)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:783)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:930)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:300)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:405)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:352)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:349)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

Basically, it seems that when getting the location of the suppressions file, the plugin does not accept the fact it is not present in the pom.

I think it should not be a problem if the suppression location is missing.

**Comment by vorburger** [comment]
> it seems that when getting the location of the suppressions file, the plugin does not accept the fact it is not present in the pom. I think it should not be a problem if the suppression location is missing.

Hm, interesting fine. Where I use this project there is a [suppressionsLocation](https://github.com/opendaylight/odlparent/blob/master/odlparent/pom.xml#L1165) (for this [checkstyle-suppressions.xml](https://github.com/opendaylight/odlparent/blob/master/checkstyle/src/main/resources/checkstyle-suppressions.xml)), so never hit this, but I guess this should be fixed... are you going to raise a PR? :smile:

**Comment by victornoel** [comment]
I will yes, I was just wondering what changed and if maybe you or @erwint had a more global point of view on the problem :)

**Comment by victornoel** [comment]
I suppose it happened here: 54a84c3ee671679372578863539e2b34fc002ea4

I will try to find an elegant and general solution.
