### ISSUE TITLE
ConfigurationException: could not locate resource [...] would be more helpful if it inclued more details

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#199]
I just hit the following, and would find it much more helpful if it included more details about where it was trying to find that `spotbugs-exclude.xml` file which it can't find...

```
ERROR: org.eclipse.m2e.core code=0 Could not update project org.opendaylight.infrautils.jobcoordinator-impl configuration
com.basistech.m2e.code.quality.shared.ConfigurationException: could not locate resource [spotbugs-exclude.xml]
  at com.basistech.m2e.code.quality.shared.AbstractMavenPluginConfigurationTranslator.copyUrlResourceToProject(AbstractMavenPluginConfigurationTranslator.java:123)
  at com.basistech.m2e.code.quality.spotbugs.MavenPluginConfigurationTranslator.setExcludeFilterFiles(MavenPluginConfigurationTranslator.java:116)
  at com.basistech.m2e.code.quality.spotbugs.EclipseSpotbugsProjectConfigurator.buildSpotbugsPreferences(EclipseSpotbugsProjectConfigurator.java:114)
  at com.basistech.m2e.code.quality.spotbugs.EclipseSpotbugsProjectConfigurator.handleProjectConfigurationChange(EclipseSpotbugsProjectConfigurator.java:93)
  at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.configure(AbstractMavenPluginProjectConfigurator.java:139)
  at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
  at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
  at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:288)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:175)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
  at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
  at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
  at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
  at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1336)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:143)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:133)
  at org.eclipse.oomph.setup.maven.impl.MavenImportTaskImpl.perform(MavenImportTaskImpl.java:392)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3334)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3277)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4504)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4498)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4496)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3268)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3243)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3143)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Anyone wants to have a go at raising at PR that improves? :smile:

**Comment by Serranya** [comment]
Seems not too difficult. I will take a look at this.
