### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by xuniyuqi** [m2e-code-quality/m2e-code-quality#20]
org.eclipse.core.runtime.CoreException: Error(s) occurred gathering items for installation
	at org.eclipse.m2e.internal.discovery.operation.MavenDiscoveryInstallOperation.computeInstallableUnits(MavenDiscoveryInstallOperation.java:131)
	at org.eclipse.m2e.internal.discovery.operation.MavenDiscoveryInstallOperation.run(MavenDiscoveryInstallOperation.java:95)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Contains: Unable to read repository at http://m2e-code-quality.github.com/m2e-code-quality/site/1.0/content.xml.
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
	at org.eclipse.ecf.provider.filetransfer.httpclient.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:232)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Contains: Error installing Checkstyle M2E contacting repository http://m2e-code-quality.github.com/m2e-code-quality/site/1.0/

**Comment by ArloL** [comment]
Please use the correct update site: http://m2e-code-quality.github.io/m2e-code-quality/site/latest

If there are any other problems, open a new issue.
