### ISSUE TITLE
m2e checkstyle does not work in multimodule project

### ISSUE THREAD

**Issue by apetrelli** [m2e-code-quality/m2e-code-quality#299]
Configuring maven-checkstyle-plugin in a parent project of a multi-module project does not cause m2e checkstyle plugin configure the checks for modules inside the parent project.
I attached the failing example (bug-demo-parent.zip) and the example that works (bug-demo-itworks.zip) that is in fact a plain single module project.

[bug-demo-itworks.zip](https://github.com/m2e-code-quality/m2e-code-quality/files/9631434/bug-demo-itworks.zip)
[bug-demo-parent.zip](https://github.com/m2e-code-quality/m2e-code-quality/files/9744675/bug-demo-parent.zip)

**Comment by adangel** [comment]
Thanks for the report. However, I can't reproduce the behavior with the following project: 
[bug-demo-parent.zip](https://github.com/m2e-code-quality/m2e-code-quality/files/9741087/bug-demo-parent.zip)

Start eclipse with a fresh workspace, import "bug-demo-parent" as an existing maven project, wait until it is completely imported and built. Then modify the parent's pom.xml file and add the checkstyle plugin (see the comments). Save it - wait until eclipse rebuilds the project. Now checkstyle is activated and markers appear in the child project.

Which version of eclipse are you using?

>  inside the parent project.

The parent project is of packaging type "pom" - so it doesn't have any source code to be checked by checkstyle. But it is enabled for the child modules.

**Comment by adangel** [comment]
Oh, it could also be a incompatibility of checkstyle, that is used in maven-checkstyle-plugin (which provides the checkstyle configuration) and the one, that is used in eclipse-cs.

E.g. maven-checkstyle-plugin 3.2.0 requires uses by default checkstyle 9.3...

I used maven-checkstyle-plugin 3.2.0 and eclipse-cs 10.0.0, eclipse 2022-09 and m2e-code-quality 2.0.0

**Comment by apetrelli** [comment]
I am using exactly the same versions, however I don't know if we are taking into account the OS, I am using Ubuntu 22.04.

When I try to do Maven -> Update project on the parent pom I see two errors with the same content in the error log.

Exception stack trace:
```
net.sf.eclipsecs.core.util.CheckstylePluginException: Failed to resolve RuleSet from inlineConfig or configLocation,SKIPPING Eclipse checkstyle configuration
	at com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.getRuleset(MavenPluginConfigurationTranslator.java:106)
	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.buildCheckstyleConfiguration(EclipseCheckstyleProjectConfigurator.java:118)
	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.handleProjectConfigurationChange(EclipseCheckstyleProjectConfigurator.java:97)
	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:141)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:857)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:827)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:982)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:323)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:386)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:205)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1093)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:338)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Session data:
```
eclipse.buildId=4.25.0.I20220831-1800
java.version=18.0.1.1
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product
```

**Comment by adangel** [comment]
Thanks for the updated project - I could reproduce the problem.

When m2e-code-quality tries to resolve the `configLocation` property, it only searches in the classpath of the plugin. But the configuration in this case is on the file system - in the parent project of the module. This case obviously is handled by maven-checkstyle-plugin (see [configureResourceResolver](https://github.com/apache/maven-checkstyle-plugin/blob/master/src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java#L767-L777) and [MCHECKSTYLE-131](https://issues.apache.org/jira/browse/MCHECKSTYLE-131)).

I'll add the same behavior in m2e-code-quality.

Btw. for multi-module-projects the proper way to share such configurations is documented here: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html - you create a separate module called "build-tools" which contains the configuration and which is added to the maven-checkstyle-plugin classpath.

**Comment by apetrelli** [comment]
Thanks @adangel!

**Comment by adangel** [comment]
@apetrelli You can use the snapshot update site -> https://m2e-code-quality.github.io/m2e-code-quality-p2-site/snapshot/
I'm not sure, when I'll release the next version.

**Comment by apetrelli** [comment]
@adangel it works perfectly on my Eclipse installation, thanks!
