### ISSUE TITLE
EclipsePmdProjectConfigurator fails if ruleset file is shorter than 100 characters

### ISSUE THREAD

**Issue by harbulot** [m2e-code-quality/m2e-code-quality#322]
This is a corner case, but the plugin fails when trying to read a very basic ruleset file like so (because it's under 100 characters):

```xml
<?xml version="1.0"?>
<ruleset xmlns="http://pmd.sourceforge.net/ruleset/2.0.0">
</ruleset>
```

Here is the exception:

```
java.lang.IndexOutOfBoundsException: Range [0, 100) out of bounds for length 93
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:76)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:313)
	at java.base/java.util.Objects.checkFromToIndex(Objects.java:385)
	at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:664)
	at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.loadXmlStreamIntoString(EclipsePmdProjectConfigurator.java:242)
	at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.locatePmdRules(EclipsePmdProjectConfigurator.java:203)
	at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.createOrUpdateEclipsePmdConfiguration(EclipsePmdProjectConfigurator.java:155)
	at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.handleProjectConfigurationChange(EclipsePmdProjectConfigurator.java:119)
	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.configure(AbstractMavenPluginProjectConfigurator.java:110)
```

The is due to [this line in `EclipsePmdProjectConfigurator.loadXmlStreamIntoString(...)`](https://github.com/m2e-code-quality/m2e-code-quality/blob/3b74ec59f2a8b2e72d27c1d303a09094eeb00089/com.basistech.m2e.code.quality.pmd/src/main/java/com/basistech/m2e/code/quality/pmd/EclipsePmdProjectConfigurator.java#L242):

```java
String prolog = decoded.subSequence(0, 100).toString();
```

I think something like this should fix the issue:

```java
String prolog = decoded.subSequence(0, Math.min(100, decoded.length())).toString();
```

**Comment by adangel** [comment]
Thanks for reporting!

**Comment by harbulot** [comment]
@adangel Thanks for fixing it!
