### ISSUE TITLE
NPE: Cannot update a project configuration after dependency project closed

### ISSUE THREAD

**Issue by dmatej** [m2e-code-quality/m2e-code-quality#4]
1) I have a project A with dependency B. Both are imported in a workspace and open.
2) I closed the project B
3) NPE on Update Project Configuration or Update Maven Dependencies, settings lost
4) Unistalled the PMD configuration plugin for M2Eclipse 1.0.0.201106081737
5) Update Project configuration works

!ENTRY org.eclipse.core.jobs 4 2 2011-07-11 15:31:17.599
!MESSAGE An internal error occurred during: "Updating Maven Configuration".
!STACK 0
java.lang.NullPointerException
	at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.createPmdRuleSet(EclipsePmdProjectConfigurator.java:223)
	at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.createOrUpdateEclipsePmdConfiguration(EclipsePmdProjectConfigurator.java:182)
	at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.handleProjectConfigurationChange(EclipsePmdProjectConfigurator.java:102)
	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:145)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:753)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:724)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:847)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:280)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:280)
	at org.eclipse.m2e.core.ui.internal.UpdateConfigurationJob.runInWorkspace(UpdateConfigurationJob.java:87)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.m2e.logback.appender 4 0 2011-07-11 15:31:17.610
!MESSAGE An internal error occurred during: "Updating Maven Configuration".

**Comment by ArloL** [comment]
Hi @dmatej, I am trying to cleanup the issues. Is this still a problem? Please let me know and I will look into it.

**Comment by dmatej** [comment]
Hi, I think this problem is fixed. I can see some nullpointers, but they can be resolved by the project update and they have nothing to do with PMD.
