### ISSUE TITLE
Build errors when Checkstyle configuration resides in workspace project

### ISSUE THREAD

**Issue by sewe** [m2e-code-quality/m2e-code-quality#40]
(This may be related to issue #32.)

When using a plugin configuration like the following

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-checkstyle-plugin</artifactId>
	<version>2.10</version>
	<dependencies>
		<dependency>
			<groupId>org.eclipse.recommenders</groupId>
			<artifactId>coding-conventions</artifactId>
			<version>${recommenders-version}</version>
		</dependency>
	</dependencies>
	<executions>
		<execution>
			<id>check-coding-conventions</id>
			<goals>
				<goal>check</goal>
			</goals>
			<configuration>
				<configLocation>checkstyle/config.xml</configLocation>
			</configuration>
		</execution>
	</executions>
</plugin>
```

an import as "Existing Maven project" fails with error multiple messages like the following:

```
Unable to update Maven configuration
Could not get configured mojo for org.apache.maven.plugins:maven-checkstyle-plugin:2.10:check {execution: check-coding-conventions}
Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.10 or one of its dependencies could not be resolved: Failure to find org.eclipse.recommenders:coding-conventions:jar:2.0.5-SNAPSHOT in http://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced
```

Apparently, the Checkstyle m2e connector cannot deal with the situation where the Checkstyle configuration is not (yet) available through a Maven repository but *is* available in the Eclipse workspace (respectively the reactor; thus, the above works when building on the command line).

FWIW, the project to reproduce this is mirrored on Github: https://github.com/eclipse/recommenders/.

**Comment by ArloL** [comment]
Please try with the latest develop build:

http://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by sewe** [comment]
I tried the latest development build, but still have the same problem:

The project’s `Properties > Checkstyle > Local Check Configurations` shows this error message: `Location "jar:file:/Users/sewe/.m2/repository/org/eclipse/recommenders/coding-conventions/2.1.12-SNAPSHOT/coding-conventions-2.1.12-SNAPSHOT.jar!/checkstyle/config.xml` of check configuration "maven-checkstyle-plugin check-coding-conventions" can't be resolved.” Apparently, the `Import > Existing Maven Projects` didn’t realize that the `org.eclipse.recommenders:coding-conventions:2.1.12-SNAPSHOT` project was imported as well and Checkstyle could simply be pointed at the `config.xml` in the current workspace.

**Comment by ArloL** [comment]
Could you try a mvn install on your coding conventions?

I am not sure that resolving in the local workspace is actually possible. `org.eclipse.recommenders:coding-conventions:2.1.12-SNAPSHOT` is a dependency of `maven-checkstyle-plugin` and not the project. Therefore I don't think that workspace resolution works there.

My knowledge in this regard is very limited and documentation scarce. So please excuse that I can't be really helpful.

**Comment by ArloL** [comment]
There actually is a bug for this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=395065

It seems that the behaviour is intended even though we're not trying to run code.

A workaround is to add the coding-conventions as a project dependency and place the checkstyle configuration in src/main/resources.

**Comment by sewe** [comment]
As I said in an earlier comment, doing a `mvn install` prior to the import is indeed a workaround, although it would of course be far nicer to have *live* editing capabilities, i.e., to be able to change the `config.xml` within the workspace and immediately see the effects without an intermediate `install` step.

I realize that documentation is missing, but @coderplus did some great work on workspace resolution for the `maven-dependency-plugin` and `maven-remote-resources-plugin`. Have a look at coderplus/m2e-connector-for-maven-remote-resources-plugin#1 and the corresponding commit for inspiration. Hope that helps.

**Comment by sewe** [comment]
In reply to https://github.com/m2e-code-quality/m2e-code-quality/issues/40#issuecomment-70060147: The situation with the `maven-remote-resources-plugin` is indeed a bit different, as it has a dedicated `<resourceBundles>` configuration option, whereas the `maven-checkstyle-plugin` can re-use its plugin dependencies for that.

**Comment by ArloL** [comment]
Sorry, about not reading the entire thread first.

I am looking into his maven-dependency-plugin work right now. It'd be really cool if this worked!

**Comment by ArloL** [comment]
I tried unpacking a local workspace dependency with the m2e-MDP by coderplus and it did not work. The maven remote resources plugin actually works but it executes the actual mojo so there seems to be something going on there.

**Comment by ArloL** [comment]
The maven remote resources plugin uses an ArtifactResolver that is injected via plexus. I don't know how to get plexus to give me one. So that didn't really work. Do you have any further ideas?

**Comment by sewe** [comment]
In reply to https://github.com/m2e-code-quality/m2e-code-quality/issues/40#issuecomment-70088909: No, I’m afraid I don’t have any further ideas, but maybe @coderplus can help you as the author of the m2e connector for the maven-remote-resources-plugin.

**Comment by ArloL** [comment]
To document my findings so far for future reference:

Both m2e connectors for maven-remote-resources-plugin and maven-dependencies-plugin simply execute the maven mojo. This does not work this case.

We need to resolve the location of e.g. the checkstyle xml somehow. Currently this is done by the [ResourceResolver](https://github.com/m2e-code-quality/m2e-code-quality/blob/f8e36f0f6fa5fa618624ac674279a181d87834cd/com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/ResourceResolver.java).
The `ClassRealm pluginRealm` is what gives us the reference to the local maven repository. Thus requiring the `mvn install` step. If we could somehow use the same logic that m2e uses for referencing projects in the same workspace we could probably figure out the location of the checkstyle.xml in the workspace. We can get the dependencies of the plugin [here](https://github.com/m2e-code-quality/m2e-code-quality/blob/f8e36f0f6fa5fa618624ac674279a181d87834cd/com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginProjectConfigurator.java#L267) by calling `mojoExecution.getPlugin().getDependencies();`. Maybe we can get a class that does the project resolution and then get the URL for the resource from the workspace project!?

Otherwise one could add the checkstyle dependency as a build dependency and let m2e do the figuring out of the workspace project. Then we compare the plugin dependencies with the build dependencies and get the URL that way!?

**Comment by ArloL** [comment]
Append for the second option: `mavenProject.getArtifacts()` gives us the build dependencies and `Artifact.getFile();` the location of the target folder of that project :) I think that might be a possible way.

**Comment by ArloL** [comment]
I think I have it: 8e8c36965baa0540650890c1278ac3ec6a383146

I have published a snapshot to https://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by ArloL** [comment]
Did you get a chance to test the snapshot, @sewe? Or @briandealwis?

**Comment by sewe** [comment]
> Did you get a chance to test the snapshot, @sewe?

Thanks for addressing this issue and publishing a snapshot. Unfortunately, I encountered a bug.

1. Install *Eclipse IDE for Java Developers* (Mars.2)
2. Install *Checkstyle integration plugin for M2Eclipse* from https://m2e-code-quality.github.io/m2e-code-quality/site/develop/
3. Exit Eclipse
4. git clone http://git.eclipse.org/gitroot/recommenders/org.eclipse.recommenders.git into workspace.
5. Start Eclipse and perform an *Import > Maven > Existing Maven Projects*

The import fails with a NPE:

    java.lang.NullPointerException
    	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.getResourceResolver(AbstractMavenPluginProjectConfigurator.java:299)
    	at com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.newInstance(MavenPluginConfigurationTranslator.java:525)
    	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.handleProjectConfigurationChange(EclipseCheckstyleProjectConfigurator.java:89)
    	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:181)
    	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:1000)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:783)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:919)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:299)
    	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:252)
    	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:168)
    	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
    	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:136)
    	at org.eclipse.m2e.core.ui.internal.wizards.ImportMavenProjectsJob$1.doCreateMavenProjects(ImportMavenProjectsJob.java:68)
    	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectsOperation.run(AbstractCreateMavenProjectsOperation.java:62)
    	at org.eclipse.m2e.core.ui.internal.wizards.ImportMavenProjectsJob.runInWorkspace(ImportMavenProjectsJob.java:77)
    	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

I hope this is enough information for you to reproduce this issue.

**Comment by ArloL** [comment]
Thanks for testing the snapshot and for the feedback! I have added a null-check and updated the develop update site. I tested the recommenders project and it worked for me. Could you try again?

**Comment by sewe** [comment]
> Could you try again?

Of course.

1. Deleted all projects in the workspace
2. Installed the lasted snapshot
3. Closed Eclipse
4. Deleted `~/.m2/repository/org/eclipse/recommenders`
5. Started Eclipse and performed a *Import > Maven > Existing Maven Projects*

This led to lots of errors like the following in the Error Log:

    org.eclipse.core.runtime.CoreException: Could not get configured mojo for org.apache.maven.plugins:maven-checkstyle-plugin:2.12:check {execution: check-coding-conventions}
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getConfiguredMojo(MavenImpl.java:364)
    	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.getResourceResolver(AbstractMavenPluginProjectConfigurator.java:306)
    	at com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.newInstance(MavenPluginConfigurationTranslator.java:525)
    	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.handleProjectConfigurationChange(EclipseCheckstyleProjectConfigurator.java:89)
    	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:181)
    	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:1000)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:783)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:919)
    	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:299)
    	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:252)
    	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:168)
    	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
    	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:136)
    	at org.eclipse.m2e.core.ui.internal.wizards.ImportMavenProjectsJob$1.doCreateMavenProjects(ImportMavenProjectsJob.java:68)
    	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectsOperation.run(AbstractCreateMavenProjectsOperation.java:62)
    	at org.eclipse.m2e.core.ui.internal.wizards.ImportMavenProjectsJob.runInWorkspace(ImportMavenProjectsJob.java:77)
    	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
    Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.12 or one of its dependencies could not be resolved: Failure to find org.eclipse.recommenders:coding-conventions:jar:2.4.0-SNAPSHOT in http://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced
    	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:218)
    	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
    	at org.eclipse.m2e.core.internal.project.registry.EclipsePluginDependenciesResolver.resolve(EclipsePluginDependenciesResolver.java:59)
    	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:422)
    	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:385)
    	at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:231)
    	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getConfiguredMojo(MavenImpl.java:352)
	... 21 more
    Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.eclipse.recommenders:coding-conventions:jar:2.4.0-SNAPSHOT in http://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
    	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:210)
	... 27 more
    Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.eclipse.recommenders:coding-conventions:jar:2.4.0-SNAPSHOT in http://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced
    	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
    	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 30 more

Apparently, its looking on the local Maven repository, even though the `coding-conventions` project has been imported into the workspace along with all the other projects, so maybe its a timing issue. But doing a *Maven > Update Projects* after all the projects have been imported, doesn’t fix the issue, but just causes the above to reappear in the Error Log.

FYI, both the global (*Preferences > Checkstyle*) and per-project (*Properties > Checkstyle*) Checkstyle configuration hasn’t been changed; it uses the `Google Checks` rather than our own Checkstyle config.

**Comment by ArloL** [comment]
I have updated the develop site with a new snapshot that does not require all dependencies to resolve.

**Comment by sewe** [comment]
Still seeing the same error (or a very similar one) after the update:

    org.eclipse.core.runtime.CoreException: Could not get configured mojo for org.apache.maven.plugins:maven-checkstyle-plugin:2.12:check {execution: check-coding-conventions}
    	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getConfiguredMojo(MavenImpl.java:364)
    	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.getResourceResolver(AbstractMavenPluginProjectConfigurator.java:307)
    	at com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.newInstance(MavenPluginConfigurationTranslator.java:533)
    	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.handleProjectConfigurationChange(EclipseCheckstyleProjectConfigurator.java:89)
    	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.configure(AbstractMavenPluginProjectConfigurator.java:137)
    	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
    	at org.sonatype.tycho.m2e.internal.TychoLifecycleMapping.configure(TychoLifecycleMapping.java:57)

On the plus side, my `target/classes` folder is already populated with my remote resources on a clean build.

**Comment by ArloL** [comment]
Well that log is expected: https://github.com/m2e-code-quality/m2e-code-quality/blob/develop/com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginProjectConfigurator.java#L313

But the configuration should work.

1. Install Eclipse IDE for Java Developers (Mars.2)
2. Install Checkstyle integration plugin for M2Eclipse from https://m2e-code-quality.github.io/m2e-code-quality/site/develop/
3. git clone http://git.eclipse.org/gitroot/recommenders/org.eclipse.recommenders.git into workspace.
4. perform an Import > Maven > Existing Maven Projects
5. Restart Eclipse for the discovered plugins
6. Confirm Checkstyle Configuration of org.eclipse.recommenders.apidocs project that it uses the workspace location

**Comment by ArloL** [comment]
This has been released now. Please let me know if there are any issues.
