### ISSUE TITLE
UnsupportedOperationException from PMD m2e connector

### ISSUE THREAD

**Issue by jwilson1066** [m2e-code-quality/m2e-code-quality#45]
I just installed the latest J2EE Eclipse and imported a POM that refers to PMD (among other plugins). I then got repeated errors like this:

An internal error occurred during "Updating Maven Project".

java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.createPmdRuleSet(EclipsePmdProjectConfigurator.java:223)
	at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.createOrUpdateEclipsePmdConfiguration(EclipsePmdProjectConfigurator.java:184)
	at com.basistech.m2e.code.quality.pmd.EclipsePmdProjectConfigurator.handleProjectConfigurationChange(EclipsePmdProjectConfigurator.java:103)
	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:145)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:965)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:746)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:865)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:289)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:369)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:316)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:161)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:137)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:89)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1301)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:313)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

Further details:

eclipse.buildId=4.3.2.M20140221-1700
java.version=1.8.0
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/jwilson/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/jwilson/.eclipse_keyring -showlocation

Plugins installed:

  Checkstyle configuration plugin for M2Eclipse	1.0.0.201307281919	com.basistech.m2e.code.quality.checkstyle.feature.feature.group	null
  EclEmma Java Code Coverage	2.3.0.201403192240	com.mountainminds.eclemma.feature.feature.group	Mountainminds GmbH & Co. KG
  Eclipse IDE for Java EE Developers	2.0.2.20140224-0000	epp.package.jee	null
  m2e connector for build-helper-maven-plugin	0.15.0.201207090124	org.sonatype.m2e.buildhelper.feature.feature.group	Sonatype, Inc.
  PMD configuration plugin for M2Eclipse	1.0.0.201307281919	com.basistech.m2e.code.quality.pmd.feature.feature.group	null

**Comment by ArloL** [comment]
Sorry about the delay. I've just pushed a new release. Please let me know if it was fixed or whether the issue still exists!

**Comment by ArloL** [comment]
Since I haven't heard anything back for three months I'll go ahead and assume it works now. Otherwise simply open a new issue or reopen this one.
