### ISSUE TITLE
FindBugs: Loading exclude filter file fails if Maven extension feature is used

### ISSUE THREAD

**Issue by res1st** [m2e-code-quality/m2e-code-quality#49]
Hi,

I want to share the exclude filter file.
That's why I'm using the Maven extension mechanism, but it fails in Eclipse.

The project de.example.buildtools contains the exclude filter file at
   src\main\resources\findbugs\excludeFilter.xml

I'm using the same mechanism for the checkstyle configuration file and it works fine.

Maven configuration:
```
<build>
   <extensions>
      <extension>
         <groupId>de.example</groupId>
         <artifactId>de.example.buildtools</artifactId>
      </extension>
   </extensions>

   <plugin>
      <groupId>org.codehaus.mojo</groupId>
      <artifactId>findbugs-maven-plugin</artifactId>
      <version>2.5.4</version>
      <configuration>
         <excludeFilterFile>findbugs/excludeFilter.xml</excludeFilterFile>
      ...
   </plugin>
</build>
```

Exception:
```
com.basistech.m2e.code.quality.shared.ConfigurationException: [M2E-FB]: could not locate resource [findbugs/excludeFilter.xml]
	at com.basistech.m2e.code.quality.findbugs.MavenPluginConfigurationTranslator.copyUrlResourceToProject(MavenPluginConfigurationTranslator.java:297)
	at com.basistech.m2e.code.quality.findbugs.MavenPluginConfigurationTranslator.setExcludeFilterFiles(MavenPluginConfigurationTranslator.java:120)
	at com.basistech.m2e.code.quality.findbugs.EclipseFindbugsProjectConfigurator.buildFindbugsPreferences(EclipseFindbugsProjectConfigurator.java:110)
	at com.basistech.m2e.code.quality.findbugs.EclipseFindbugsProjectConfigurator.handleProjectConfigurationChange(EclipseFindbugsProjectConfigurator.java:82)
	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:145)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:959)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:747)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:876)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:291)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:154)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:89)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:166)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:142)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:96)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by dan-skiffington** [comment]
Did you ever figure this out?  I'm running into the same thing.

**Comment by Dawuid** [comment]
Problem is related with commit https://github.com/m2e-code-quality/m2e-code-quality/commit/6840c009e49add41331209422eb8276f344b1b53#diff-45a0545fba8b9bd9242ce9213c76e09f method getPluginClassRealm.

Those files, include/exclude filters, are not searched any more like a resource because MojoExecution returns a null ClassRealm, so ResourceResolver cannot explore all possibilities (resources, URL, files). With previous code, MavenSession was recovered previously and MojoExecution was updated with that kind of data.

**Comment by ArloL** [comment]
I have reverted parts of that commit and updated the develop site. Thanks for finding the problem.

http://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by balazs-zsoldos** [comment]
I have a similar problem. I have just updated to the version that is available in the master branch today. Till now everything worked file, but now I get the following exception:

    com.basistech.m2e.code.quality.shared.ConfigurationException: [M2E-FB]: could not locate resource [everit-findbugs.xml]
	at com.basistech.m2e.code.quality.findbugs.MavenPluginConfigurationTranslator.copyUrlResourceToProject(MavenPluginConfigurationTranslator.java:350)
	at com.basistech.m2e.code.quality.findbugs.MavenPluginConfigurationTranslator.setExcludeFilterFiles(MavenPluginConfigurationTranslator.java:133)
	at com.basistech.m2e.code.quality.findbugs.EclipseFindbugsProjectConfigurator.buildFindbugsPreferences(EclipseFindbugsProjectConfigurator.java:114)
	at com.basistech.m2e.code.quality.findbugs.EclipseFindbugsProjectConfigurator.handleProjectConfigurationChange(EclipseFindbugsProjectConfigurator.java:85)
	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:112)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:1000)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:783)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:919)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:299)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:154)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:89)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by ArloL** [comment]
Sorry about the delay. I've just pushed a new release. Please let me know if it was fixed or whether the issue still exists!

**Comment by balazs-zsoldos** [comment]
Everything works well for me with the latest m2e snapshot. Thanks!

**Comment by ArloL** [comment]
Thanks for your feedback. I will go ahead and close this issue then.
