### ISSUE TITLE
NullPointerException with maven-checkstyle-plugin 2.13

### ISSUE THREAD

**Issue by berndv** [m2e-code-quality/m2e-code-quality#53]
**Problem**
When using maven-checkstyle-plugin 2.13 an NPE occurs in MavenPluginConfigurationTranslator when importing or building projects in Eclipse.

**Reason**
MavenPluginConfigurationTranslator looks up the paramaters `sourceDirectory` and `testSourceDirectory` directory. Those are deprecated since 2.13 and replaced by the parameters `sourceDirectories` and `testSourceDirectories`.

**Workaround**
Use maven-checkstyle-plugin 2.12...

---

```xml
<build>
	<plugins>
		<plugin>
			<artifactId>maven-checkstyle-plugin</artifactId>
			<version>2.13</version>
			<executions>
				<execution>
					<id>checkstyle</id>
					<phase>verify</phase>
					<goals>
						<goal>check</goal>
					</goals>
				</execution>
			</executions>
			<configuration>
				<configLocation>${sonar.checkstyle.url}</configLocation>
			</configuration>
		</plugin>
	</plugins>
</build>
```

```
eclipse.buildId=unknown
java.version=1.7.0_67
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -pluginCustomization plugin_customization.ini
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -pluginCustomization plugin_customization.ini

org.eclipse.m2e.core
Error
Sun Oct 05 17:54:45 CEST 2014
Errors running builder 'Maven Project Builder' on project 'srcpit-parent'.

java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.getIncludesExcludesFileMatchPatterns(MavenPluginConfigurationTranslator.java:343)
	at com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.updateCheckConfigWithIncludeExcludePatterns(MavenPluginConfigurationTranslator.java:159)
	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.buildCheckstyleConfiguration(EclipseCheckstyleProjectConfigurator.java:145)
	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.handleProjectConfigurationChange(EclipseCheckstyleProjectConfigurator.java:102)
	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:145)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:959)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:747)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:876)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:291)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:154)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:89)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:166)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:142)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:96)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)


```

**Comment by ArloL** [comment]
Please test with this update site: http://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by ArloL** [comment]
Should be fixed with latest release.
