### ISSUE TITLE
NullPointerException at AbstractPMDRecord.findResource

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#94]
I've seen this a few times today, perhaps the respective code could be hardened:

    Exception:java.lang.NullPointerException: null
	 at net.sourceforge.pmd.eclipse.ui.model.AbstractPMDRecord.findResource(AbstractPMDRecord.java:246)
	 at net.sourceforge.pmd.eclipse.ui.views.ChangeEvaluator.searchProjectForModifications(ChangeEvaluator.java:161)
	 at net.sourceforge.pmd.eclipse.ui.views.ChangeEvaluator.updateFiles(ChangeEvaluator.java:121)
	 at net.sourceforge.pmd.eclipse.ui.views.ChangeEvaluator.changeRecordFor(ChangeEvaluator.java:81)
	 at net.sourceforge.pmd.eclipse.ui.views.ViolationOverviewContentProvider.resourceChanged(ViolationOverviewContentProvider.java:330)

This is m2e-code-quality version 1.0.0.201602071612.

**Comment by ArloL** [comment]
Thanks for the report, @vorburger.

Looking at the packages in the stacktrace that seems to be an issue with the pmd-eclipse-plugin. Are you sure it's an issue with this project?

**Comment by vorburger** [comment]
@ArloL you are absolutely right of course, sorry for my confusion.

I've raised this on https://sourceforge.net/p/pmd/bugs/1507/.

Closing.
